package com.beacon.analyticscollection.model;

public enum EventType {
    LOGIN, LOGOUT,
    PASSWORD_CHANGE_REQUEST, PASSWORD_CHANGE_SEND_EMAIL, PASSWORD_CHANGE_CLICK_EMAIL, PASSWORD_CHANGE_COMPLETED
}
